services:
  zirc_chat_server:
    container_name: zirc_chat_server
    # image: zirc_chat_server
    env_file: ./Chat_Server/.env
    build:
      context: ./Chat_Server
      dockerfile: Dockerfile
    ports:
      - "6667:6667" # irc server
      - "7000:7000" # server manager
    depends_on:
      - zirc_db
    networks:
      zirc_subnet:
        ipv4_address: 172.20.0.4
    secrets:
      - s2s_password

  # Used as a an additional server to test multi-server setup
  zirc_animalhouse:
    container_name: zirc_animalhouse
    env_file: ./Chat_Server/.env
    environment:
      - IRC_SERVER_DNS_NAME=animal-houseIRC.io
    build:
      context: ./Chat_Server
      dockerfile: Dockerfile
    ports:
      - "6600:6667" # irc server
      - "7070:7000" # server manager
    depends_on:
      - zirc_db
    networks:
      zirc_subnet:
        ipv4_address: 172.20.0.6
    secrets:
      - s2s_password
    profiles:
      - multi

  zirc_nickserv:
    container_name: zirc_nickserv
    # image: zirc_nickserv
    env_file: ./NickServ/.env
    build:
      context: ./NickServ
      dockerfile: Dockerfile
    networks:
      zirc_subnet:
        ipv4_address: 172.20.0.2

  zirc_db:
    image: postgres:17
    container_name: zirc_db
    environment:
      - PGUSER=postgres
      - PGPASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - $HOME/zirc_chat_db:/var/lib/postgresql/data
      - ./db/postgres/pgdump.sql:/pgdump.sql
      - ./db/postgres/restore.sh:/docker-entrypoint-initdb.d/restore.sh
      - ./db/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      zirc_subnet:
        ipv4_address: 172.20.0.3

  zirc_test_client:
    env_file: ./Chat_Server/TestClient/.env
    build:
      context: ./Chat_Server/TestClient
      dockerfile: Dockerfile
    container_name: zirc_test_client
    networks:
      zirc_subnet:
        ipv4_address: 172.20.0.5

networks:
  zirc_subnet:
    ipam:
      config:
        - subnet: 172.20.0.0/16

secrets:
  s2s_password:
    file: ./Chat_Server/secrets/s2s_password