server:
  server_version: "v1.0.0"
  server_role: "leaf" # one of leaf, hub, hybrid ... or root?
  super_admin_password_file: "/run/secrets/super_admin_password"
  server_name: "ZZ.IRC"
  server_description: "super fun zzirc server"
  dns_name: "zzirc.com"
  ts6_enabled: true
  capabilities: "sasl account-registration"
  # capabilities:
  # - sasl
  # - account-registration
  supported_auth_types: "PLAIN,SCRAM-SHA-256,OAUTHBEARER,EXTERNAL"
  # o: IRC operator
  # i: Invisible (user won't appear in channel user lists unless they are in the same channel)
  # w: Receive wallops (messages sent to all IRC operators)
  # s: Receive server notices
  # Note: Just because a mode is listed here doesn't mean the user currently has it; it just indicates that the mode is available on the server.
  user_modes: "oiws"
  # see mode.go for full list of channel modes
  channel_modes: "beiklmnopPst"
  # NOTE DONT FORGET: this password is intended for CLIENT access to the server, NOT S2S!
  # password should be generated and hashed then entered here
  # **NOTE** you must escape `$` characters otherwise they are interpolated as variables
  # Use the below hash as a test password - the password is 1235
  # IRC_SERVER_PASSWORD="\$2a\$10\$RFRaJiN40EzL9.nvfq4uy.w6UHs7WuF3EkBpxj.xUPjNd8tUs7sfi"
  # password_file: "/run/secrets/server_password"
  init_worker_count: 3
  max_buffer_size: 8192
  max_user_channels: 20
  server_manager_port: "7000"
  host: "0.0.0.0"
  port: "6667"
  tls_port: "6697"
  tls_cert_path: "./.tls/server.crt"
  tls_key_path: "./.tls/server.key"
  enable_tls: false
  irc_verison: "302"
  supported_protocol_versions: "302"
  use_user_pass: "true" # When true, will not ask the user to authenticate again to use chat, but will log them in via their password automatically
  chat_server_log_level: "3" # info https://pkg.go.dev/github.com/phuslu/log@v1.0.110#Level
  ping_pong_timeout: 2
  ping_pong_timeout_duration: "minute"
  ping_pong_enabled: false

db:
  enabled: false
  host: "zirc_db"
  port: "5432"
  user: "postgres"
  # password_file: "/run/secrets/db_password"
  database: "postgres"
  application_name: "zirc_server"
  enable_tls: false
  tls_cert_path: "./.tls/db.crt"
  tls_key_path: "./.tls/db.key"
  healthcheck_interval: 2

s2s:
  # password_file: "/run/secrets/s2s_password"
  port: "7000"
  tls_port: "7001"
  enable_tls: false
  tls_cert_path: "./.tls/s2s.crt"
  tls_key_path: "./.tls/s2s.crt"
  max_buffer_size: 262144 # 256KB